import pygame
WIDTH, HEIGHT = 1000, 500
ROAD_WIDTH, ROAD_HEIGHT = 100, 200
PARK_WIDTH, PARK_HEIGHT = 75, 150

#Level one boundaries
BOUNDARY_ONE = pygame.Rect(199, HEIGHT - ROAD_WIDTH - ROAD_HEIGHT, 1, 300)
BOUNDARY_TWO = pygame.Rect(299, HEIGHT - ROAD_HEIGHT, 1, 200)
BOUNDARY_THREE = pygame.Rect(199, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH, ROAD_HEIGHT * 3 - PARK_WIDTH * 2, 1)
BOUNDARY_FOUR = pygame.Rect(299, HEIGHT - ROAD_HEIGHT, ROAD_HEIGHT * 3 - ROAD_WIDTH, 1)
BOUNDARY_FIVE = pygame.Rect(799, 125, 1, ROAD_WIDTH + PARK_WIDTH)
BOUNDARY_SIX = pygame.Rect(650, 125, PARK_HEIGHT, 1)
BOUNDARY_SEVEN = pygame.Rect(650, 125, 1, PARK_WIDTH)

lvl1_boundaries = [BOUNDARY_ONE, BOUNDARY_TWO, BOUNDARY_THREE, BOUNDARY_FOUR, BOUNDARY_FIVE, BOUNDARY_SIX, BOUNDARY_SEVEN]

#Level 2 boundaries
BOUNDARY_ONE_TWO = pygame.Rect(200, HEIGHT - ROAD_HEIGHT, ROAD_HEIGHT * 3, 1)
BOUNDARY_TWO_TWO = pygame.Rect(200, HEIGHT - ROAD_HEIGHT * 2 - 50, 1, ROAD_HEIGHT + 50)
BOUNDARY_THREE_TWO = pygame.Rect(300, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH, ROAD_HEIGHT * 2 + 25, 1)
BOUNDARY_FOUR_TWO = pygame.Rect(200, HEIGHT - ROAD_HEIGHT * 2 - 50, ROAD_WIDTH, 1)
BOUNDARY_FIVE_TWO = pygame.Rect(725, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH - PARK_HEIGHT , 1, PARK_HEIGHT)
BOUNDARY_SIX_TWO = pygame.Rect(725, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH - PARK_HEIGHT , PARK_WIDTH, 1)
BOUNDARY_SEVEN_TWO = pygame.Rect(800, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH - PARK_HEIGHT , 1, PARK_HEIGHT + ROAD_WIDTH)
BOUNDARY_EIGHT_TWO = pygame.Rect(300, HEIGHT - ROAD_HEIGHT - ROAD_WIDTH * 2 - 50, 1, PARK_HEIGHT)

lvl2_boundaries = [BOUNDARY_ONE_TWO, BOUNDARY_TWO_TWO, BOUNDARY_THREE_TWO, BOUNDARY_FOUR_TWO, BOUNDARY_FIVE_TWO, 
BOUNDARY_SIX_TWO, BOUNDARY_SEVEN_TWO, BOUNDARY_EIGHT_TWO]